export const USER_LOG_IN = 'USER_LOG_IN'
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS'
export const USER_LOG_IN_FAILURE = 'USER_LOG_IN_FAILURE'

export const USER_LOG_OUT = 'USER_LOG_OUT'
export const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS'
export const USER_LOG_OUT_FAILURE = 'USER_LOG_OUT_FAILURE'

export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'

export const USER_CONFIRM = 'USER_CONFIRM'
export const USER_CONFIRM_SUCCESS = 'USER_CONFIRM_SUCCESS'
export const USER_CONFIRM_FAILURE = 'USER_CONFIRM_FAILURE'

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST'
export const USER_RESET_PASSWORD_REQUEST_SUCCESS = 'USER_RESET_PASSWORD_REQUEST_SUCCESS'
export const USER_RESET_PASSWORD_REQUEST_FAILURE = 'USER_RESET_PASSWORD_REQUEST_FAILURE'

export const USER_VALIDATE_TOKEN = 'USER_VALIDATE_TOKEN'
export const USER_VALIDATE_TOKEN_SUCCESS = 'USER_VALIDATE_TOKEN_SUCCESS'
export const USER_VALIDATE_TOKEN_FAILURE = 'USER_VALIDATE_TOKEN_FAILURE'

export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD'
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS'
export const USER_RESET_PASSWORD_FAILURE = 'USER_RESET_PASSWORD_FAILURE'

export const FETCH_BOOKS = 'FETCH_BOOKS'
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE'

export const CREATE_BOOK = 'CREATE_BOOK'
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS'
export const CREATE_BOOK_FAILURE = 'CREATE_BOOK_FAILURE'

export const SEARCH_BOOKS = 'SEARCH_BOOKS'
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS'
export const SEARCH_BOOKS_FAILURE = 'SEARCH_BOOKS_FAILURE'

export const REMOVE_BOOK = 'REMOVE_BOOK'
export const REMOVE_BOOK_SUCCESS = 'REMOVE_BOOK_SUCCESS'
export const REMOVE_BOOK_FAILURE = 'REMOVE_BOOK_FAILURE'
